name: Docker Build & Push CI CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub (using a secret)
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and tag the Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/munni-algo:latest .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/munni-algo:latest ${{ secrets.DOCKERHUB_USERNAME }}/munni-algo:$(git rev-parse --short HEAD)

      - name: Push the Docker image (with tags)
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/munni-algo:latest
          